artifacts_root : artifacts


data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
  local_data_file : artifacts/data_ingestion/airline.csv

EDA :
 data_path : artifacts/data_ingestion/airline.csv
 report_path : artifacts/EDA/report 
 data_output : artifacts/EDA

model : 
 data_path : artifacts/EDA/eda_data.csv
 report : artifacts/model
 model_save_path : artifacts/model/

prediction:
 auto_arima : artifacts/model/auto_arima.pkl
 prophet : artifacts/model/prophet.pkl
 
